language: julia
julia:
  - release
  - nightly
notifications:
    email: false
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia --check-bounds=yes -e 'Pkg.build("Divergences"); Pkg.test("Divergences"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Divergences")); Pkg.add("Coverage");using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'

